name: Build And Push To DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '17'

      - name: Check cache
        id: check-cache
        uses: actions/cache@v3.2.6
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Gradle Build Action
        run: ./gradlew clean assemble
        
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_TCR_USERNAME }}
          password: ${{ secrets.TENCENT_TCR_PASSWORD }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          tags: fengwenhao/gradle-ci
          context: .
          addLatest: true
          addTimestamp: true
          push: true
