name: Build And Push To DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get Timestamp Action
        id: get-time
        uses: nanzm/get-time-action@v2.0
        with:
          timeZone: Asia/Shanghai
          format: YYYYMMDDHHmmss
          
      - name: Echo
        run: |
          echo ${{ steps.get-time.outputs.time }}
      
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up JDK
#         uses: actions/setup-java@v1.4.4
#         with:
#           java-version: '17'

#       - name: Gradle Build Action
#         run: ./gradlew clean assemble

#       - name: Docker Build
#         run: docker build -t fengwenhao/gradle-ci .
      
#       - name: Docker Login
#         uses: docker/login-action@v2.2.0
#         with:
#           username: fengwenhao
#           password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
#       - name: Docker Push
#         run: docker push fengwenhao/gradle-ci
